services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: mtn-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  mailpit:
    image: axllent/mailpit
    container_name: mtn-mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
